<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="VentanaTools.Orbit.Extensions" Version="$(VentanaExtensionsVersion)" />
    <Compile Remove="tests/**/*.cs" />
    <None Update="extension.json" CopyToOutputDirectory="PreserveNewest" />
    <InternalsVisibleTo Include="CountdownExtensionSample.Tests" />
  </ItemGroup>
</Project>
